import fs from "fs";
import path from "path";

const CARDS_DIR = path.join(process.cwd(), "r2_backup/data/cards");
const OUTPUT_FILE = path.join(process.cwd(), "r2_backup/data/variants.json");

const CHAMPIONSHIP_VARIANTS = [
  "akiraMiyazaki",
  "alejandroNg",
  "andreChiasson",
  "andrewEstrada",
  "chaseMoloney",
  "chrisFulop",
  "christopherKan",
  "clementLamberton",
  "codyWalinski",
  "curranHill",
  "davidCohen",
  "diegoCassiraga",
  "dylanLefavour",
  "evanPavelsk",
  "fernandoCifuentes",
  "gabrielFernandez",
  "gustavoWada",
  "harukiMiyamoto",
  "harutoKobayashi",
  "henryBrand",
  "hirokiYano",
  "ianWhiton",
  "igorCosta",
  "jacobVanWagner",
  "jasonKlaczynski",
  "jasonMartinez",
  "jeremyMaron",
  "jeremyScharff",
  "jesperEriksen",
  "jesseParker",
  "jimmyBallard",
  "junHasebe",
  "kabuFukase",
  "karaLichtleitner",
  "kayaLichtleitner",
  "kevinNguyen",
  "magnusPedersen",
  "michaelGonzalez",
  "michaelPramawat",
  "michikazuTsuda",
  "miskaSaari",
  "mychaelBryan",
  "naohitoInoue",
  "naotoSuzuki",
  "ondrejSkubal",
  "ondrejSkubalWcd",
  "patrickMartinez",
  "paulAtanassov",
  "pedroEugenioTorres",
  "reedWeichler",
  "rikutoOhashi",
  "robinSchulz",
  "rossCawthon",
  "rowanStavenow",
  "sakuyaOta",
  "sebastianLashmet",
  "shaoTongYen",
  "shintaroIto",
  "shuntuSadahiro",
  "shutoItagaki",
  "stephenSilvestro",
  "takashiYoneda",
  "tomRoos",
  "tordReklev",
  "trentOrndorff",
  "tristanRobinson",
  "tsubasaNakamura",
  "tsuguyoshiYamato",
  "vanceKelley",
  "yugoSato",
  "yukaFurusawa",
  "yutaKomatsuda",
  "zacharyBokhari"
];

const GRANDMASTER_VARIANTS = [
  "asiaChampionshipStamp",
  "asiachampionshipstamp",
  "battleRoadStamp",
  "battleRoadStampAlternate",
  "battleRoadStampAlternate2",
  "championStamp",
  "league1stPlaceStamp",
  "league2ndPlaceStamp",
  "league3rdPlaceStamp",
  "league4thPlaceStamp",
  "leagueStamp",
  "nationalChampionshipsStamp",
  "playPokemonThankYouStamp",
  "professorProgramStamp",
  "professorProgramStampReverseHolofoil",
  "regionalChampionshipsStaffStamp",
  "regionalChampionshipsStamp",
  "top32stamp",
  "winnerStamp",
  "worldChampionshipsStaffStamp",
  "worldChampionshipsStamp",
  "staffStamp",
  "expansionStaffStamp",
  "prereleaseStaffStamp",
  "originsGameFairStaffStamp",
  "jumbo",
  "jumboAlternate",
  "goldBorder",
  "metal",
  "normalUnnumbered",
  "latinStamp",
  "playPokemonStampHolofoil",
  "playPokemonStampReverseHolofoi",
  "playPokemonStampReverseHolofoil",
  "anniversaryStamp",
  "armarougeStamp13",
  "armarougeStamp15",
  "armarougeStamp19",
  "armarougeStamp30",
  "armarougeStamp33",
  "armarougeStamp34",
  "armarougeStamp43",
  "armarougeStamp47",
  "armarougeStamp48",
  "armarougeStamp51",
  "armarougeStamp55",
  "armarougeStamp56",
  "buildAbearStamp",
  "burgerKingExpansionStamp",
  "burgerKingStamp",
  "charizardStamp1",
  "charizardStamp13",
  "charizardStamp14",
  "charizardStamp15",
  "charizardStamp16",
  "charizardStamp18",
  "charizardStamp21",
  "charizardStamp23",
  "charizardStamp25",
  "charizardStamp26",
  "charizardStamp27",
  "charizardStamp28",
  "charizardStamp30",
  "charizardStamp31",
  "charizardStamp33",
  "charizardStamp34",
  "charizardStamp36",
  "charizardStamp37",
  "charizardStamp39",
  "charizardStamp4",
  "charizardStamp40",
  "charizardStamp41",
  "charizardStamp42",
  "charizardStamp43",
  "charizardStamp44",
  "charizardStamp45",
  "charizardStamp46",
  "charizardStamp47",
  "charizardStamp48",
  "charizardStamp49",
  "charizardStamp50",
  "charizardStamp51",
  "charizardStamp52",
  "charizardStamp53",
  "charizardStamp54",
  "charizardStamp55",
  "charizardStamp56",
  "charizardStamp57",
  "charizardStamp58",
  "charizardStamp59",
  "charizardStamp60",
  "charizardStamp7",
  "cinderaceStamp1",
  "cinderaceStamp13",
  "cinderaceStamp14",
  "cinderaceStamp15",
  "cinderaceStamp17",
  "cinderaceStamp18",
  "cinderaceStamp19",
  "cinderaceStamp21",
  "cinderaceStamp23",
  "cinderaceStamp25",
  "cinderaceStamp27",
  "cinderaceStamp28",
  "cinderaceStamp30",
  "cinderaceStamp31",
  "cinderaceStamp33",
  "cinderaceStamp34",
  "cinderaceStamp36",
  "cinderaceStamp37",
  "cinderaceStamp39",
  "cinderaceStamp4",
  "cinderaceStamp40",
  "cinderaceStamp41",
  "cinderaceStamp42",
  "cinderaceStamp43",
  "cinderaceStamp44",
  "cinderaceStamp45",
  "cinderaceStamp46",
  "cinderaceStamp47",
  "cinderaceStamp48",
  "cinderaceStamp49",
  "cinderaceStamp50",
  "cinderaceStamp51",
  "cinderaceStamp52",
  "cinderaceStamp53",
  "cinderaceStamp54",
  "cinderaceStamp55",
  "cinderaceStamp56",
  "cinderaceStamp57",
  "cinderaceStamp58",
  "cinderaceStamp59",
  "cinderaceStamp7",
  "comicConStamp",
  "darkraiStamp",
  "detectivePikachuStamp",
  "e3stamp",
  "ebGamesStamp",
  "eeveeStamp",
  "expansionStamp",
  "gamesExpoStamp",
  "gamestopStamp",
  "genConStamp",
  "gymChallengeStamp",
  "holidayStamp",
  "ionoStamp",
  "legendaryPokemonStamp",
  "mewtwoStamp",
  "movieStamp",
  "originsGameFairStamp",
  "originsStamp",
  "pikachuStamp1",
  "pikachuStamp13",
  "pikachuStamp14",
  "pikachuStamp15",
  "pikachuStamp16",
  "pikachuStamp18",
  "pikachuStamp19",
  "pikachuStamp2",
  "pikachuStamp20",
  "pikachuStamp23",
  "pikachuStamp24",
  "pikachuStamp25",
  "pikachuStamp26",
  "pikachuStamp28",
  "pikachuStamp29",
  "pikachuStamp30",
  "pikachuStamp32",
  "pikachuStamp33",
  "pikachuStamp34",
  "pikachuStamp36",
  "pikachuStamp37",
  "pikachuStamp38",
  "pikachuStamp40",
  "pikachuStamp41",
  "pikachuStamp42",
  "pikachuStamp44",
  "pikachuStamp45",
  "pikachuStamp46",
  "pikachuStamp47",
  "pikachuStamp49",
  "pikachuStamp5",
  "pikachuStamp50",
  "pikachuStamp51",
  "pikachuStamp52",
  "pikachuStamp53",
  "pikachuStamp54",
  "pikachuStamp55",
  "pikachuStamp56",
  "pikachuStamp57",
  "pikachuStamp58",
  "pikachuStamp59",
  "pikachuStamp6",
  "pikachuStamp60",
  "playPokemonStamp",
  "pokeTourStamp",
  "pokemonCenterStamp",
  "pokemonDayStamp",
  "pokemonHorizonsStamp",
  "pokemonRocksAmericaStamp",
  "pokemonTogetherStamp",
  "prereleaseStamp",
  "rainCityShowcaseStamp",
  "scryeStamp",
  "sevenElevenStamp",
  "snowflakeStamp",
  "stamp",
  "stamp22",
  "toysRusStamp",
  "wStamp"
];

const FULL_SET_PRIORITY = [
  "normal",
  "unlimited",
  "unlimitedShadowless",
  "holofoil",
  "unlimitedHolofoil",
  "firstEdition",
  "firstEditionHolofoil"
];

async function main() {
  // 1. Create variants.json
  const variantsConfig = {
    championship: CHAMPIONSHIP_VARIANTS.sort((a, b) => a.localeCompare(b)),
    grandmaster: GRANDMASTER_VARIANTS.sort((a, b) => a.localeCompare(b)),
    fullSetPriority: FULL_SET_PRIORITY
  };

  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(variantsConfig, null, 2), "utf-8");
  console.log(`Created ${OUTPUT_FILE}`);

  // 2. Strip variantTags from card set JSON files
  const files = fs.readdirSync(CARDS_DIR).filter(f => f.endsWith('.json'));
  console.log(`Found ${files.length} card files to clean up.`);

  let totalCardsCleaned = 0;
  let filesModified = 0;

  for (const file of files) {
    const filePath = path.join(CARDS_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const cards = JSON.parse(content);
    let modified = false;

    for (const card of cards) {
      if ('variantTags' in card) {
        delete card.variantTags;
        modified = true;
        totalCardsCleaned++;
      }
    }

    if (modified) {
      fs.writeFileSync(filePath, JSON.stringify(cards, null, 2), 'utf-8');
      filesModified++;
    }
  }

  console.log(`Cleaned up ${totalCardsCleaned} cards across ${filesModified} files.`);
}

main().catch(console.error);
